### ISSUE TITLE
Editor "internal" debugger use the user config package.path not the lualibs

### ISSUE THREAD

**Issue by zuzmo** [pkulchenko/ZeroBraneStudio#1058]
bin/linux/x64/lua: src/editor/debugger.lua:7: module 'copas' not found:
	no field package.preload['copas']
	no file 'home/zuzmo/programs/lua/lua5.3.5/share/lua/5.3/copas.lua'
	no file '/home/zuzmo/programs/lua/lua5.3.5/share/lua/5.3/copas/init.lua'
	no file '/home/zuzmo/programs/lua/lua5.3.5/lib/lua/5.3/copas.so'
stack traceback:
	[C]: in function 'require'
	src/editor/debugger.lua:7: in main chunk
	[C]: in function 'dofile'
	src/main.lua:597: in main chunk
	[C]: at 0x00404f08

**Comment by pkulchenko** [comment]
@zuzmo, I'm not sure what exactly the issue is here. It seems like you modified the IDE source and now it can't find the copas modules required for its debugger functionality. I'd prefer not to use the system modules, as I can't guarantee that they are compatible with what's being shipped, that's why the modules are included with the IDE package (and tested to ensure they work on all supported platforms).
