### ISSUE TITLE
require'lfs' in Local console crash IDE.

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#1079]

**Comment by pkulchenko** [comment]
It doesn't for me; any further details? version, platform?

**Comment by robertlzj** [comment]
Win10, newest IDE and `lfs.dll` in folder clib53.
I'll try on another computer later.

**Comment by pkulchenko** [comment]
Yes, it has to be related if you run it from clibs53, as the version to be loaded from the console has to be linked with lua51. I'm certain that it's related to the wrong version to be loaded, but can you run `print(package.cpath)` from the console to confirm?

**Comment by robertlzj** [comment]
`print(package.cpath)` from _local console_ is different from neither _run_ nor _debug_.
```lua
--local console
bin/clibs/?.dll;
C:\Users\RobertLin\AppData\Roaming\LuaRocks\lib\lua\5.3\?.dll;
c:\programfiles\zerobranestudio\\lib\lua\5.3\?.dll;
C:\Users\RobertLin\luaplus\Tools\JamPlus\bin\win32\lua\modules\?.dll;
```
`lfs` would been first found at `c:\programfiles\zerobranestudio\\lib\lua\5.3\?.dll;`, if `\\` won't trouble.
Or, been found at `C:\ProgramFiles\ZeroBraneStudio\bin\clibs\` expanded for `bin/clibs/?.dll;`.
But in both position, I put the right `lfs.dll` already.
So, why crashes still happen?

**Comment by robertlzj** [comment]
New test. Script `print(require'lfs')` in editor using Lua 5.1 won't work, print nothing but complete script with no waring in Output.
Same script in _console_ make crash.

**Comment by pkulchenko** [comment]
> Script print(require'lfs') in editor using Lua 5.1 won't work, print nothing with no waring in Output, just complete script.
> Same script in console make crash.

It's because when you Run or Debug your application, it's executed in a separate process, which crashes, but leaves your IDE process intact. When you try to load a wrong library into the same process as the IDE, it crashes and takes down everything with it, including the IDE.

Your path information confirms that you are loading a library from lua53 into the process that expect lua51 library, which will lead to a crash.

The question is, how did you get lua53 path into the one used by the Local console, as it should reference only paths for lua51 modules by default. Did you set it up in LUA_CPATH before loading the IDE or in user.lua?

**Comment by robertlzj** [comment]
My fault. I did modify **LUA_CPATH** in environment variables. Now I restore them (almost empty now).

**Comment by pkulchenko** [comment]
Right, you can use LUA53_CPATH, but shouldn't put lua53 libraries in LUA_CPATH.
