### ISSUE TITLE
IDE remains in tray but won't start (MacOS, Catalina)

### ISSUE THREAD

**Issue by NimrodSegall** [pkulchenko/ZeroBraneStudio#1085]
The Zerobrane main window won't come up every now and then when calling it. This is fixable by deleting the session configuration file, as suggested by Paul Kulchenko, in [this thread](https://stackoverflow.com/questions/63481198/zerobrane-studio-wont-run-macos).

**Comment by pkulchenko** [comment]
@NimrodSegall, can you save the session configuration file next time this happens, email it to an email in the footer of https://studio.zerobrane.com, and update the ticket? I'm trying to figure out what may be incorrect in the session data and have not been able to reproduce it so far.

**Comment by NimrodSegall** [comment]
I'll do that the next time it occurs. Thanks =)

**Comment by NimrodSegall** [comment]
Here it is. Renamed as .txt so that github allows it to be uploaded.


[ZeroBraneStudio Preferences.txt](https://github.com/pkulchenko/ZeroBraneStudio/files/5565023/ZeroBraneStudio.Preferences.txt)

**Comment by pkulchenko** [comment]
@NimrodSegall, thank you for the sample. Unfortunately, I don't see any failure on my machine when I use it (maybe because the paths are different). Can you try copying it again to its location (so it would fail), but running the following command: `cd /Applications/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio; bin/lua src/main.lua` (adjust the path to the app if needed)? It may report the actual error in the command line; I'm interested in the stack trace of the error. Thanks!

**Comment by pkulchenko** [comment]
Possibly related to #859.
