### ISSUE TITLE
remote debugging debugger.redirect = "c" does only capture print, but not io.write or io.stdout:write

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#1109]
I'm struggling with capturing output.
Running ZBS on a linux or Windows host (should not matter)
There I have debugger.redirect = "c" in .zbstudio/user.lua set.

Doing Remote debug on an arm device basically using code sililar to this
```lua
	local script={}
	push(script,sprintf("arg={[0]=%q}",filename))
	push(script,sprintf('require("mobdebug").loop("%s")',ZBSHOSTNAME))
	local cmd=sprintf("/usr/bin/luajit -e'%s'&",join(script,';'))
	remote_execute(cmd)
```
(where push=table.insert, join=table.concat and sprintf=string.format)

Now, when debugging remote, I can see output of
`print("using print")` in ZBS Output window, but I cannot see `io.write('using io.write()\n')` or `io.stdout:write('using io.stdout:write()\n')`

Is this an incompleteness in mobdebug? Any chance for a quick fix or workaround?

**Comment by pkulchenko** [comment]
It's mostly by design, as `io.write` and `io.stdout:write` are used less frequently and I wanted to have an alternative for some output to not be redirected. In terms of the workaround, you can probably apply the same logic to `io.write` as is applied to `print` (it's in mobdebug.lua on lines 1006-1020). This code intercepts the `print` call and sends its content back to the IDE. Another option is to assign `io.write` based on `print` in your code after `require "mobdebug".start()` is executed.

**Comment by jjvbsag** [comment]
Thank you for you response. I will try and come back to you.
