### ISSUE TITLE
Problems with using clibs on Win10

### ISSUE THREAD

**Issue by asket-stubborn** [pkulchenko/ZeroBraneStudio#1119]
ZeroBraneStudio\bin/clibs/winapi.dll
when adding your own libraries or using standard clibs, it processes Linux-style slashes inside a folder, everything is fine up to the folder with the program. A hex error occurs due to the mixing of styles.

ㄥ⃥￫￱圠湩㈳. - it's when I copy to browser
![изображение_2021-08-20_125347](https://user-images.githubusercontent.com/2909104/130215816-0f8e2b6a-7db1-4fd5-bab3-9134b402adb3.png)

**Comment by pkulchenko** [comment]
There is something else going on, as the mixed slashes won't stop Lua from loading a correct module. How are you loading the winapi.dll module and what version of Lua are you using? This looks like a case when modules for different versions of Lua are mixed together.

**Comment by asket-stubborn** [comment]
5.3 and winapi that in kit with Studio only. I try to use it with lua 5.3 and love. And there is that case

**Comment by pkulchenko** [comment]
That's the problem, because winapi packaged with the IDE is for Lua 5.1 and you won't be able to use it with Lua 5.3. You'll need to compile winapi.dll for Lua 5.3. You can use the build scripts that come with the IDE as long as you have the mingw/gcc compiler configured. You can then run `(cd build; bash build-win32.sh lua 5.3 winapi)` to compile the library for Lua 5.3. You can also download a [pre-compiled winapi for Lua 5.3](https://download.zerobrane.com/misc/winapi53.dll).
