### ISSUE TITLE
Paste single line in case of rectangle selection

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#1123]
Lets say clipboard contains some text e.g. `aaa` and text editor has lines like
```
123456
123456
```
Then if create rectangle selection with zero width (put cursor at the beging of document) and press `Alt-Shit-Down` and then do past from clipboard (e.g. press `Ctrl-V`) the result text will be
```
aaa23456
aaa23456
```
Note of missing the `1` symbol in each line.

**Comment by pkulchenko** [comment]
Indeed, although it appears to be a Scintilla issue, as I don't see any handling of the rectangular selection in the IDE itself. I'll think of a workaround and am open to suggestions. I was thinking about adding a "fake" character, but it's not a good idea in case this issue gets fixed (or is already fixed in some later version of Scintilla).

**Comment by moteus** [comment]
But there no such effect in the SciTE text editor. (I have 3.5 and 5.11 versions)
By the way is there any plans to update scintilla versioin?

**Comment by pkulchenko** [comment]
There is nothing newer available wxwidgets unfortunately. I pushed several times to get a new version incorporated, but it hasn't happened yet.

I'll check again if there is anything happening in the IDE itself, but so far I don't see it. Maybe it was specific to the version of Scintilla we were using...

**Comment by pkulchenko** [comment]
Found the problem; should be fixed now. Thank you for the report!
