### ISSUE TITLE
Broken selection replace

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#1125]
Trying this code from the local console
```
e = ide:GetEditor(); e:SetText('-- local str = [[ `voo` ]]\r\n'); e:Refresh(); e:Update(); e:SetSelection(0,28); e:ReplaceSelection('local str = [[ `voo` ]]\r\n');
```
I've got 
```Lua
-- local str = [[ `voo` ]]
local str = [[ `voo` ]]
```
Note that without `Refresh/Update` I got 
```Lua
local str = [[ `voo` ]]
```
So I belive its something related with comment styles.

**PS.** I solve this with `DeleteRange` / `InsertText`
```
e = ide:GetEditor(); e:SetText('-- local str = [[ `voo` ]]\r\n'); e:Refresh(); e:Update(); e:DeleteRange(0,28); e:InsertText(0, 'local str = [[ `voo` ]]\r\n');
```

**Comment by pkulchenko** [comment]
@moteus, it's not "broken", it's a side-effect of the markdown markup in comments, which hides some of the characters, and hidden characters are not removed by `Cut` and `ReplaceSelection` calls. `DeleteRange` does ignore those, so that's why it works.

`ReplaceTarget` should work as well, so you may want to use that (although you'll have to use `SetTargetStart` and `SetTargetEnd` to mark the target). Also see #827.
