### ISSUE TITLE
Ctrl+Tab should use LRU order for traversing the tabs

### ISSUE THREAD

**Issue by madmaxoft** [pkulchenko/ZeroBraneStudio#301]
Most IDEs support this feature, it makes using the editor natural. Pressing `Ctrl`+`Tab` once toggles between the two last recently used tabs. Holding the `Ctrl` key down and pressing `Tab` activates the next-last-recently used tab, further `Tab` presses move further down the "recentness". Only when the `Ctrl` key is released is the current tab marked as the new last recently used tab.

**Comment by 4aiman** [comment]
> If you want to implement your own logic, I can help you with wrapping it into a plugin. I can tell you that the queue-navigation logic ended up being not as simple as I'd like it to be.

I'd like some help here.

**Comment by pkulchenko** [comment]
@4aiman, you'd need to come up with some logic first. Associating functions with shortcuts and menu items is not difficult. For example, check [overtype plugin](https://github.com/pkulchenko/ZeroBranePackage/blob/master/overtype.lua) that adds a menu item and registers a handle for it.

You'd need to identify what tab you want to go to or what file to open. You can then use `ide:LoadFile(fname)` to load file and this will take care of activating it if it's already loaded in the IDE.

You can also keep track of loaded/saved files using `onEditorLoad` and `onEditorSave` events (check `packages/sample.lua` file for parameters). This is mostly the same list as is shown in `File | Recent Files` and that's why I suggested looking at that list to see what's already available.

**Comment by 4aiman** [comment]
@pkulchenko the logic was described in the issue opened by me and closed by you :)

Anyways, thanks for the tip. I'll check that out.

**Comment by pkulchenko** [comment]
> the logic was described in the issue opened by me and closed by you :)

Yes, but it's incomplete as it only describes one case.

Let's say the last three visited files are A, B, C (with the last one being currently open). `Ctrl-Tab` will activate B; what will next `Ctrl-Tab` activate, A or C? If A, then it violates your description, but if C, then it violates the logic for `Ctrl-Tab,Tab` vs `Ctrl-Tab` and `Ctrl-Tab` (which makes it inconsistent).

There are also questions whether `Ctrl-Tab` or `Ctrl-Shift-Tab` should be moving back in the queue (as `Ctrl-Shift-Tab` looks like a better match). Also, `Ctrl-(Shift-)Tab` is sort of "wired" to navigate the tabs the way it currently is, but other shortcuts already navigate the queue of recently used files.

**Comment by 4aiman** [comment]
@pkulchenko No offense, but you really should take a peek on how other IDEs are doing that or else this won't go anywhere further. (Although the ```won't do``` speaks loud and clear).

```crtl+tab``` activates the last file only when both keys are released.
In case ```ctrl``` is still pressed and tab has been released, the changes to the list of tabs are not to be applied. 

Take a look at this (I think it should be clear where ```ctrl+tab,tab``` begins)
![image](https://www.dropbox.com/s/a2l9ofj7pzqt7y7/vid.ogv.gif?dl=1)

Here's a description of ```ctrl+tab``` behavior from Geany's readme:
>Switches to the previously shown document (if it's still open). Holding Ctrl (or another modifier if the keybinding has been changed) will show a dialog, then repeated presses of the keybinding will switch to the 2nd-last used document, 3rd-last, etc. Also known as Most-Recently-Used documents switching.

(Although that descripton from geany makes no sense to me it may be otherwise for you ;)

**Comment by pkulchenko** [comment]
>> Here's a description of ctrl+tab behavior from Geany's readme:

> Switches to the previously shown document (if it's still open). Holding Ctrl (or another modifier if the keybinding has been changed) will show a dialog, then repeated presses of the keybinding will switch to the 2nd-last used document, 3rd-last, etc. Also known as Most-Recently-Used documents switching.

Right; this is exactly what the IDE does with the most-recently-viewed file.

You should be able to implement whatever logic you prefer as a plugin ([as explained earlier](https://github.com/pkulchenko/ZeroBraneStudio/issues/301#issuecomment-317826771)) and link it to a shortcut; you won't be able to link it to Ctrl-Tab though due to the constraints imposed by wxwidgets, but other shortcuts are available.
