### ISSUE TITLE
Multipaste

### ISSUE THREAD

**Issue by sclark39** [pkulchenko/ZeroBraneStudio#311]
When multiple lines are selected, paste should write into all selected lines.

According to the documentation, it seems like this should be as easy as just:
editor:SetMultiPaste(1) 
...but when I try this it doesn't seem to change anything. Not sure if there is something interfering in ZeroBrane or if this is a wxLua/wxwidgets issue.

**Comment by cipri-tom** [comment]
so it seems fixed in the wxwidgets ... any chance it will come into ZBStudio soon? :D

**Comment by pkulchenko** [comment]
It is indeed fixed; I have been planning wxwidgets upgrade for quite some time, but it boils down to several things: (1) find a way to keep binaries (especially wx library) separately to avoid increasing the size of the repository, and (2) check if bugs are fixed in wxwidgets, (3) upgrade and test. This is likely to require a separate release just to distribute and test the upgrade. I'll update #260 with more specific plans.

**Comment by pkulchenko** [comment]
Closed by the completion of #260 (merged wxwidgets31x-upgrade branch).
