### ISSUE TITLE
Specs not loaded

### ISSUE THREAD

**Issue by jacobdufault** [pkulchenko/ZeroBraneStudio#395]
Sorry, I might not be using ZBS correctly, but I have this HTML file (foo.html)

```html
<!-- okay -->
<node>
  <element foo="okay">
    hello
  </element>
</node>
```

When I load it in ZBS I get this:
![image](https://cloud.githubusercontent.com/assets/356714/5727074/5a2a7fec-9b2e-11e4-8ef0-2ac033ecee34.png)

However, the presence of `spec/html.lua` implies to me that there should be syntax highlighting. Is this the expected output? I'm using the current master (commit 1829e78d05d20fddd09b9e68444fb6457e56ad22) and I have not made any modifications to settings or the like.

**Comment by pkulchenko** [comment]
@jacobdufault, you are doing everything correctly, it's just the additional specs are not enabled by default (due to several, mostly historical, reasons).

You can enable `html` spec by adding the following to the config file:

```lua
load.specs(function(file) return file:find('spec[/\\]html%.lua$') end)
```

This example is present in `cfg/user-sample.lua`, but it needs to be better documented.

This is not ideal and I've been thinking about enabling some of the specs by default and also to allow new specs to be dropped into the folder without additional configuration steps.

**Comment by pkulchenko** [comment]
@jacobdufault, I enabled html and C/cpp specs by default, so the config setting I referenced earlier is no longer needed in your case.
