### ISSUE TITLE
ID_QUICKADDWATCH: Is it working?

### ISSUE THREAD

**Issue by andrewstarks** [pkulchenko/ZeroBraneStudio#405]
[working from  commit  81aaaef53] 

In my user.lua config file I have:

```lua
local G = ...
keymap[G.ID_QUICKADDWATCH] = 'F9'
```

I would expect this to add selected text (or if none is selected, the text surrounding the current cursor posstion, stopping at spaces or the begging/end of the token?) to the watch window.

When that failed, I tried copying the text and then hitting F9. I added other watch window hot-key overrides and they seemed to work, if I had the watch window selected.

Am I doing something wrong?

**Comment by pkulchenko** [comment]
Andrew, you have the right expectations, but in this case it doesn't quite work the expected way. Since these items are available only through a context/popup menu, they are not available through a global shortcut. The filetree popup menu works in a similar way. It is possible, but difficult to make it work without having this item available in a global menu somewhere. There are three main ways to have shortcuts in wxwidgets:  (1) have the shortcut associated with a menu item, (2) have it registered in a global accelerator table, and (3) have "hardcoded" logic in KEYPRESS or similar handler on that object.

I may add logic to put this handler in the accelerator table, but it's not clear how to select those items that need to be there. I can also add a menu item to the main menu, but I don't see a good place for it and other items need to be added as well for consistency.

Maybe a proper way to do this will be something like this: check if any of the registered IDs have a shortcut; if it's not in the main menu, then add it to the accelerator table. This should work assuming that the handler for that ID works outside of the context menu (which is not the case currently as the context menu populates the value to be worked on based on where the click target is and so on).

I need to try couple of options; open to suggestions.

**Comment by pkulchenko** [comment]
Andrew, I reviewed the code one more time and so far there is no good way to implement this. I have it on the back burner, but realistically, there are more important/interesting things that need to be done first, so this one is not likely to get implemented soon.

To capture my thoughts on this: the process I outlined earlier will work, but it requires the menu handlers (for example, the handler that is called on `ID_QUICKADDWATCH`) to be independent from any logic that is now triggered when the local menu is shown. That logic needs to be extracted and moved (when possible) to the handlers. In addition to that, `UPDATEUI` handlers (to disable/enable menu elements) need to be added to check for conditions on when those menu items should be available.

**Comment by pkulchenko** [comment]
@andrewstarks, it's been a while, but this functionality has been added to the master branch. So far this is enabled for those items that appear on the editor context menu: `ID.GOTODEFINITION, ID.RENAMEALLINSTANCES, ID.REPLACEALLSELECTIONS, ID.QUICKADDWATCH, ID.QUICKEVAL, ID.ADDTOSCRATCHPAD`. Let me know if you get a chance to try it and run into any issues.
