### ISSUE TITLE
Break at cursor

### ISSUE THREAD

**Issue by andrewstarks** [pkulchenko/ZeroBraneStudio#413]
My apologies if this is duplicate. Also, I'm happy to dig and implement when I have some time. I want to write this down here, because I'm thinking of it:

When I'm debugging, I often want to skip past a tedious section (a chunk with a table definition with lots of meta lookups can take dozens of Skip Over (F10 in my case). I want it to jump down to the next section.

Today, I will often scroll down, create a break point, F5 and then remove the breakpoint. This is okay, but tedious enough that i often just keep hitting F5.

I've seen other debuggers that allowed me to "Break at cursor position". This is a simple trick (from my perspective, not implementation) that actually has a pretty big productivity impact.

**Comment by pkulchenko** [comment]
We are talking about "Run to cursor", right?

I have thought about it as I agree, it would be convenient, but it turned out to be an interesting problem to solve. I thought about setting a one-time breakpoint (which would require extending the debugger to support that), but even that is not sufficient as the control may be stopped elsewhere (for example, on a different breakpoint), in which case the "cursor position" breakpoint should still be invalidated. Or maybe it shouldn't? I'm not sure what other IDEs do in a case like this...

It's possible to do this without any debugger support: (1) set a real breakpoint, (2) run, (3) if the stop is detected at that position, remove the breakpoint. I think this is exactly the logic that the MS debugger implements: "The debugger will internally set a breakpoint for you and remove it when your application stops at it."

I think the added convenience is that "Run to Cursor" can be used to start the debugging and run to a particular position (if `debugger.runonstart` is set)...

**Comment by pkulchenko** [comment]
@andrewstarks, added Run to Cursor to the menu and to the toolbar. It adds a temporary breakpoint that will be removed when the location is "visited" (or when debugging is aborted). This makes it work when there are other breakpoints that need to be hit before "run-to-cursor" location is reached.

Give it a try and let me know.

**Comment by andrewstarks** [comment]
ACK! Awesome! My apologies for forgetting to respond to your question! You were correct in your analysis. I'll merge and test this now. Thanks!

**Comment by andrewstarks** [comment]
FYI: Works perfect. I was showing ZBS to a JS/C# dev. He was surprised that a dynamic language could have such a nice debugger (don't know what JS debugging looks like, so I can't compare). He saw me hitting F10 a bunch of times and said, "My life got way better when MS added the Break at Cursor function."

I can't wait to show this update to him.

**Comment by pkulchenko** [comment]
Great; thank you for the suggestion and the feedback! It turned out to be more complex than I expected, but in the end I think I got it working to my liking.
