### ISSUE TITLE
"Too many open files" in find in files.

### ISSUE THREAD

**Issue by stuta** [pkulchenko/ZeroBraneStudio#441]
In OSX I have a forder structure with 2136 files (not all of them are Lua).

When I find I get:
Can't open file '/Users/.../source/lib/draw.lua': Too many open files

sysctl kern.maxfiles
kern.maxfiles: 20480

sysctl kern.maxfilesperproc
kern.maxfilesperproc: 18000

**Comment by pkulchenko** [comment]
@stuta, these seem to be kernel limits, not application limits. I also get 256 for `launchctl limit maxfiles` and 2560 for `ulimit -n`.

In any case, the IDE doesn't open that many files; there shouldn't be more than one file open at any given time during the search. The only thing I can think of is some underlying issue with `wxDir` as I only see it on OSX (I tried to search in a folder with 70k files in subfolders on Windows and don't get this issue).

I do see this on OSX, but it's sporadic. Re-running the same query in the same process may return different results; restarting the process doesn't always clear the issue, so it seems more of a system-wide limit than a process limit. I'll see if I can use lfs instead of the methods that wxwidgets provides or change the logic to avoid this...

**Comment by pkulchenko** [comment]
Also, it's likely that the issue was there before as well; I just added better error reporting when I updated the search functionality for find-in-files.

**Comment by pkulchenko** [comment]
@stuta, this should be fixed now. Give it a try and let me know.

**Comment by stuta** [comment]
Works now, thanks.
