### ISSUE TITLE
Don't rely on __tostring in watches and stack windows

### ISSUE THREAD

**Issue by s-ol** [pkulchenko/ZeroBraneStudio#457]
When using an OOP lib like 30log or middleclass `__tostr` only prints the type, showing the contents would be more useful.

Discussion happened over here: https://love2d.org/forums/viewtopic.php?f=4&t=80160

**Comment by pkulchenko** [comment]
I'm not sure what a good way to resolve this is. It's useful to rely on `__tostring` to return what the user needs in most cases; in those rare cases when this doesn't happen, it's possible to add `__serialize` method to return whatever is needed in this case. I'm also considering adding an option to disable metatable processing or an option to provide a general callback that allows users to specify how metatables should be handled.

Speaking specifically about not relying on `__tostring` in watch and stack windows, I can't do that as this is used for userdata as well as for some legitimate cases (for example, proxy tables that by themselves have no content).

In my opinion, having `__serialize` method is sufficient enough, even though it could be useful to have it as a serializer option, instead of having to add it to the objects themselves.

**Comment by S0lll0s** [comment]
Displaying both `__tostring` and optionally `__serialize` (with a switch somewhere) certainly could do the trick.

**Comment by andrewstarks** [comment]
++ on this one. This is a way to common "thing i type:

```lua
(function() return setmetatable(x, nil) end) -- or some similar solution
```

It's an issue if, especially if `__tostring` is serializing an object, like turning it into its string representation or type name (which is a common practice in some object models). You end up with x= "http://foo", with no clue as to if you have a literal string or an object that returns that string as an answer for `tostring`. 

If you could provide a way to flag a watch to use the raw version, that could work. Something like `~x` means the raw version and `x` means the overloaded. This doesn't help for the stack view. But that could have a raw flag...

Anyway. I agree that this is a "thing".

**Comment by pkulchenko** [comment]
Andrew, are you also using 30log/middleclass? Or have a different reason?

**Comment by andrewstarks** [comment]
No... I use this technique here and there. The above url example was not made up from thin air. I think that I may also be thinking of a case in Penlight, as well.

**Comment by pkulchenko** [comment]
I agree that it could be useful, but it's unfortunately very difficult to pick a side here and also difficult to make it an option as it's likely needed to be an interpreter-based one, as there are some interpreters that use `userdata` objects and rely on tostring to properly show their values. My assumption was that for objects with metatables, `tostring` is a safe/good value to use. If that's not the case, then one option to consider is to provide the "original" value in a comment, but comments are stripped in the stack/watch windows, so that needs to be taken into account somehow.

I still plan to add "raw" option to ignore metatables, but I think for the case of stack/watch values it will be better to show in comments the "original" values as you get the best of both.

**Comment by andrewstarks** [comment]
I understand you. I agree with your thinking, as well.

**Comment by robertlzj** [comment]
There is ambiguous to use the result of an object being watched - to show the **raw** value or to show the **convertted / returned** value.
I think, could show the raw one is **basal**, then then convertted one is **optional**, and only to provide some convenient.
But there is **some case** which raw is meanless, and could be replaced to user defined. - Table's **address**, especially when used as key.
Also, need some **indicator** to distinguish from them. Not to use the string value returned from __tostring directly. Like `FieddName=..` or `[[TableName]]=..`.

From #569 :
> ```
> local table = setmetatable({},{__tostring = function(self) return 'my table' end})
> table[1] = table
> table[table] = 2	--watch window will only shows 'table = "my table"'.
> ```
> 
> Could the user specified name by `__tostring` only be used to replace the **address** (like `[[table: 0x123]]` which is meanless), especially when used as key (like `table[table] = 2`).
> And so the table could **expanded**.

**Comment by pkulchenko** [comment]
The problem with showing both is that it's unclear how to figure out which to show or how to merge them. It *seems* like if one is a table and the other is not, probably the table should be shown, but what if it's empty?

> I think to give user some APIs to let them DIY how to show their watch / stack window based on uncontested raw information. like some pulgin to allow various watch / stack in multi windows contenting both raw and user-defined value.

I tend to agree; I'm considering to add an option to disable metatable/__tostring processing or to allow it to be configurable.

**Comment by pkulchenko** [comment]
I've disabled using `__tostring` in Stack/Watch windows, so the table content will be shown by default. Can still be turned on by setting `debugger.showtostring=true` in the config.
