### ISSUE TITLE
Autocomplete for "self" fields

### ISSUE THREAD

**Issue by Andy2244** [pkulchenko/ZeroBraneStudio#485]
Hi,

i would like to use ZB for CryEngines Lua files and there is also already a custom auto-complete lib for the c-binds. The main problem i noticed is that ZB auto-complete wont list any members using the self keyword and i can't seem to get access to subtables?

Example:

``` lua
Door =
{
    Properties =
    {
        bUsable = 1,
    },

    bIsActive = 0,
    locked = false,
}

DOOR_TOGGLE = 0;
DOOR_OPEN = 1;
DOOR_CLOSE = 2;

function Door:IsUsable(user)
    if (self.Properties.bUsable ~= 1) then
        return 0;
    end

    if (self.locked) then
        return 0;
    end
end

function Door:ResetAction()
    self.action = DOOR_CLOSE;
    self.rotationUpdate = nil;
    self.slideUpdate = nil;
    if AI then AI.ModifySmartObjectStates( self.id, "Closed-Open" ) end;
end

```

So typing "self." or "self.Prop" wont list any results and "Door:Prop" or "Door:IsU" wont list any either? In babelua for VS2013 i can just type "self." or "self:" and get the expected members/functions listed? Is there a way to get a similar behaviour and results?

I also can't get "goto definition" to work at all? In the ResetAction function highlighting "DOOR_CLOSE" wont even list this option?

thx
Andy

PS: I already have "staticanalyzer.infervalue = true" enabled btw.

**Comment by pkulchenko** [comment]
> So typing "self." or "self.Prop" wont list any results and "Door:Prop" or "Door:IsU" wont list any either? In babelua for VS2013 i can just type "self." or "self:" and get the expected members/functions listed?
> Is there a way to get a similar behaviour and results?

Not with the current code analyzer. It's not deep enough to figure out that `self` refers to `Door` and that the `Door` table includes specific table fields.

> I already have "staticanalyzer.infervalue = true" enabled btw.

This only reconfigures static analyzer and has no impact on other components. The static analyzer does look at table fields, but it's too slow in this mode to apply in real-time.

> I also can't get "goto definition" to work at all? In the ResetAction function highlighting "DOOR_CLOSE" wont even list this option?

It's because `DOOR_CLOSE` is a global variable that has no "definition"; if you add `local` in front of it, you'll get that option.

**Comment by Andy2244** [comment]
What do you mean by has no "definition" and what has the scope of a identifier to-do with finding out where it is defined?

I'm coming from c++/c# so i always used definition and declaration this way:

Declaration: "Somewhere, there exists a foo".
Definition: "...and here it is!"

So in all implementations of "go-to definition" i encountered so far, i will get to the place where the identifier is associated with its content/value. In this case my expectation would be to land in the line where i defined "DOOR_CLOSE"  to be "2".

Is the word "definition" or defining something used in a different sense in lua and can you explain how the scope plays into this?
I mean in general i use such a feature to quickly get to the place to see the "content" and place of a identifier and i usually don't care or would expect it to fail because of a global or local scope?

thx 
Andy

**Comment by Andy2244** [comment]
I simply compare it to babelua and there i can quickly jump to this line via "go-to definition":
```
DOOR_CLOSE = 2;
```

This helps to find where a identifier comes from, so i was confused that this is not even a option in this case. Why would i not want this feature only because something is in a global scope?

**Comment by pkulchenko** [comment]
> This helps to find where a identifier comes from, so i was confused that this is not even a option in this case. Why would i not want this feature only because something is in a global scope?

Because global variables are not defined in Lua; they are only assigned values. Where is `DOOR_CLOSE` defined in the following fragment:

```lua
if false then
  DOOR_CLOSE = 1
end
DOOR_CLOSE = 2
print(DOOR_CLOSE)
```

What if `DOOR_CLOSE` is set in two different (other) files?

> 1) Where does this identifier comes from aka to what file/class/namespace does it belong?

If you put `local` in front of it, there is no ambiguity; if it's a global variable, there is no proper answer to it.

> 2) What is its actual value/content/"function" of the identifier.

There is no straightforward way to get the answer without code evaluation; the syntax analysis is not enough. Some tools do this behind the scenes, this IDE doesn't (for now).

> 3) How does the surrounding code look like.

You can jump to the places where the variable is used by doing `Ctrl/Cmd-DblClick` in the variable and then using `FindNext/F3` and `FindPrevious/Shift-F3` to jump between instances.

As to the definition, I may suggest adding `local DOOR_CLOSE = DOOR_CLOSE` to the top of the file; if it's assigned and used only in that file, then change it to `local DOOR_CLOSE = 2` and you get the expected result.

**Comment by Andy2244** [comment]
ah thx for the explanation, seems babelua is either lucky than or does some special guessing. Just wanted to point out the differences. The main reason to switch from babelua to ZB was the already existing CryEngine autocomplete lib and the faster working speed.

Guess i need to write the custom autocomplete list for babelua than myself, since the missing deeper analysis is what makes working with Cryengines lua files and ZB really hard.

thx
Andy
