### ISSUE TITLE
bug in autocomplete (local variable and api name clash)

### ISSUE THREAD

**Issue by pixeljetstream** [pkulchenko/ZeroBraneStudio#498]
setting api = {"luajit2"} in config.lua, which is actually an undocumented cool feature ;) will enable autocomplete when typing "ffi."

in a file that starts out with
local ffi = require "ffi"
it works, but if I do
local ffi = require("ffi")
then ffi seems to become a local autocomplete word and looses the api information ("ffi." no longer brings the list of functions)

not critical given the workaround exists

**Comment by pkulchenko** [comment]
Christoph, it's actually a documented feature: http://studio.zerobrane.com/doc-general-preferences#custom-apis; you can even set different APIs for different interpreters ;).

> local ffi = require("ffi")
> then ffi seems to become a local autocomplete word and looses the api information ("ffi." no longer brings the list of functions)

I'd say it's by design as I remove everything in brackets to simplify the parsing, which removes `("ffi")` in this case. I'll take a look, but it's likely to stay this way...

**Comment by pkulchenko** [comment]
Christoph, should be fixed now. It turned out that it only worked for you by accident as `ffi` matched the name of the API; for any other variable name it wouldn't work. This has been fixed and I also fixed the handling of `require('...')` vs `require '...'`.

The last commit also updates the handling of a trickier case when you do things like:

```
local table = require"io"
local t = require"table"
```

Both `t` and `table` auto-complete should be handled correctly (before both `t` and `table` would show `io` auto-complete).

This is a strange example, but there are some legitimate cases that work in a similar way.
