### ISSUE TITLE
Prompt doesn't appear after first IO reading

### ISSUE THREAD

**Issue by DenisKolodin** [pkulchenko/ZeroBraneStudio#505]
I've catched the IO bug. This script:

    local line = io.read("*l")
    print("You type:", line)

ZBS doesn't show prompt (in Output window) and program blocks, but if I add empty stdout writing before  it works:

    print("")
    local line = io.read("*l")
    print("You type:", line)

Now I can enter input for stdin in Output window:

    >>> any data in line

**Comment by pkulchenko** [comment]
This is by design and is [documented behavior](http://studio.zerobrane.com/doc-faq#how-to-accept-keyboard-input-for-applications-started-from-the-ide). To avoid keeping the Output panel editable all the time, it's only "opened" after output to it. I may reconsider it in the future, but it hasn't been a noticeable limitation as ideally, you'd need to prompt the user anyway.
