### ISSUE TITLE
refresh symbols crashing

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#507]
This happens on the project symbol branch using linux x64. I've been trying to debug where and how but it seems almost random. I'm not experienced at all with how gdb works or debugging luajit from C.

I've disabled jit and attached this code:

	local stack = io.open("/home/caps/goluwa/ZeroBraneStudio/last_stack", "wb") 
	debug.sethook(function(event, line) 
		if event == "line" then 
			stack:write(debug.getinfo(2).source, ":", line, "\n") 
			stack:flush() 
		end 
	end, "l")

inside the coroutine wrap in outline:RefreshSymbols

On the surface at least it seems that multiple calls to RefreshSymbols will cause this crash.

**Comment by pkulchenko** [comment]
This appears to be related to #499, event though the stack traces don't show anything directly related to the symbol search. The issue happens when `on idle` event is called by the system from `PopupMenu` method (when the popup menu is displayed). If there is files re-indexing (related to symbol search) happening at this time, it leads to a crash with various stack traces, but always caused by a segmentation fault. This has only been noticed on Linux so far. I'm checking on a fix or a work-around.
