### ISSUE TITLE
standard Lua 5.1 interpreter

### ISSUE THREAD

**Issue by raingloom** [pkulchenko/ZeroBraneStudio#519]
I'm currently writing a re-implementation of the io library for MTA, which uses standard 5.1.
Since the built-in LuaJIT interpreter is built with 5.2 compatibility, some of my code that should not fail on MTA fails in ZeroBrane and vice-versa.

Disabling the compatibility feature would just cause more problems, so can we instead have a vanilla 5.1 interpreter option?

**Comment by pkulchenko** [comment]
@raingloom, I thought about it, but given that Lua 5.3 is already out, I don't think it makes much sense to bundle "original" Lua 5.1 for two reasons: (1) it's been a very rare request as it's an old version (althought I realize that it's the main version used in embedded configurations), and (2) you can easily build your own. In fact, you can use the scripts that come with ZeroBrane Studio; for example, running the following command will build Lua 5.1 interpreter and put it in the right place instead of LuaJIT interpreter: `(cd build; bash build-win32.sh lua)`.

ZeroBrane Studio itself will continue working with Lua 5.1 interpreter

**Comment by pkulchenko** [comment]
You can also reference any Lua executable by adding `path.lua = 'path/lua-executable'` to the IDE configuration.
