### ISSUE TITLE
Error program running on vera Edge on Windows10

### ISSUE THREAD

**Issue by B3rt** [pkulchenko/ZeroBraneStudio#523]
I get an error when i start to run/debug the code on a vera, see screenshot for the details.
I tested this on windows 10 and vera edge UI7.
![2015-09-11_223357](https://cloud.githubusercontent.com/assets/720614/9826011/9db86712-58d7-11e5-86c0-8b232b489a6a.png)

Is this a bug of is there something else happening here?

**Comment by pkulchenko** [comment]
@B3rt, this issue has been resolved in the version 0.90+, which provides a better handling of this situation. It should be fixed by configuring the address of your device (as described in [this section of the FAQ](https://studio.zerobrane.com/vera-faq#will-the-ide-work-with-my-device-that-is-using-ui6)), but you may want to upgrade to the version 0.90 as it provides other improvements as well.

If upgrading and configuring the device address doesn't help, please send me an email with details of your configuration.

**Comment by B3rt** [comment]
And how do i get this version?
I can not find any download or update link for it on your website?

**Comment by pkulchenko** [comment]
Send me an email to support@zerobrane.com with your information and I'll send you download details.
