### ISSUE TITLE
Running on multi-user Windows system silently fails

### ISSUE THREAD

**Issue by joshkel** [pkulchenko/ZeroBraneStudio#542]
My son tried to run ZeroBrane Studio on the family PC, running Windows 10, and it never did anything, whether it was run from its normal directory via the command line, the normal directory via Windows Explorer, or a separate download directory.

I realized that I had left it running in my user, so once I closed it, it worked fine under his account.

It would be great of ZeroBrane's single-instance feature was multi-user friendly.

**Comment by pkulchenko** [comment]
Josh, it is a rare case, but I agree, it would be nice to take that into account. Unfortunately, it's not so easy to work around that, as it's not just the fact that another instance is running; it's checked because the IDE instance is listening on a particular port to enable debugging, so multiple instances would need to listen on different ports, which complicates configuration of debugging.

I think it may be problematic to allow different instances to run on different ports by default, but it should be possible to detect that another instance is running under a different user and properly report this fact, which would allow you to troubleshoot it faster. I'll update the ticket after I do a bit of research on this.

**Comment by pkulchenko** [comment]
@joshkel, this should be fixed now. The second instance will start, but you'll still see a warning message as the debugging is not likely to work properly. It would be good if you could test this. Thanks.

**Comment by joshkel** [comment]
Works great! Thank you very much for the explanation and the quick fix.
