### ISSUE TITLE
Certain tabs do not display when clicked on OSX after restarting ZBS

### ISSUE THREAD

**Issue by abigpotostew** [pkulchenko/ZeroBraneStudio#546]
Steps:
1. Open a bunch of files in a single tabbed pane. I have 7 open. Order should not matter. 
2. Restart ZBS.
3. Click on various tabs.
4. Now click on each tab moving from right to left until you reach the first.
5. After clicking the first tab, it does not display correctly. Instead it will select another tab, or do nothing.

Repeat steps 4 and 5 until issue occurs. I can always reproduce it on the second try if not the first. The first tab is always affected, but sometimes 2 or 3 tabs are as well.

This seems like a strange bug but it affects me every time I use ZBS. I am able to reproduce with empty config file, ZBS 1.20, and Mac OS 10.10.4. I noticed this issue for previous versions of both OSX and ZBS (before v1.0 to present)

My workaround is to drag the broke tab to some other position in the tab list. This action moves the tab position but also displays the tab.

**Comment by pkulchenko** [comment]
Confirmed; taking a look at what's going on...

**Comment by pkulchenko** [comment]
@abigpotostew, it's an interesting issue. The focus actually switches to the tab you click on, but then it's switched to the next tab and the next, until it gets to the tab it "settles" on. This looks like wxwidgets issue, because it's somehow caused by `ExpandAllChildren` call in `outline.lua` (line 492), which should have no impact on that tab switching (the issue disappears when `ExpandAllChildren` call is commented out). I'm still investigating and will update when I get a fix.

**Comment by pkulchenko** [comment]
@abigpotostew, added a workaround that should fix the issue. Check on the latest master and let me know.

**Comment by abigpotostew** [comment]
@pkulchenko Seems to be working! Also it seems to have fixed an occasional crash that I could not reliably reproduce in the past.

**Comment by pkulchenko** [comment]
Cool! Thank you for the update.
