### ISSUE TITLE
Stack window error: mobdebug.lua:201: loop in gettable

### ISSUE THREAD

**Issue by hanoixan** [pkulchenko/ZeroBraneStudio#550]
I'm running the debugger server (Zerobrane 1.20) on a luajit (2.0.3) project, and in some cases I can hit a breakpoint, and my Stack window will show:

"Error: ...iles (x86)\ZeroBraneStudio\lualibs\mobdebug\mobdebug.lua:201: loop in gettable".

I investigated this, and it was happening on this line:

		local value, ktype, plainindex = t[key], type(key), n <= maxn and not sparse

When I split this out, I found it was the assignment of local value to t[key]. The contents of the t table appeared to be a key code lookup table, starting on numeric key 8. It was attempting to evaluate with key == 1, so it should have passed back nil in this case.

My current workaround is:

		local value = nil
		pcall(function()
			value = t[key] 
		end)
		local ktype = type(key)
		local plainindex = n <= maxn and not sparse

Which will swallow any errors on the access of t, and set value to nil in that case. Since adding this, I haven't seen any more stack problems. Obviously this isn't an ideal solution (it's likely a problem deep in luajit), but it got me working, and I'd assume others may have had the same problem.

**Comment by pkulchenko** [comment]
@hanoixan, thank you for the report. This may be caused by a link in `__index` metamethod. For example, the following code should trigger the same error:

```lua
local t = {}
setmetatable(t, {__index = t})
print(t.somekey)
```

The fix is to use `rawget(t, 'somekey')` instead of `t.somekey` and this is the same fix you can apply to mobdebug, but I'm not sure that's the right thing to do as this will make all metafields empty.

I haven't been able to reproduce this with the stacktrace yet, but it does seem like this is caused by a flaw in your app logic as to get into this situation you'd need to **have some key** (so `ipairs` would return it), but **don't really have the key** to trigger a metamethod.

Can you try to reproduce it on a small example, such that I could run it locally and it would trigger that error in the stack trace?

**Comment by hanoixan** [comment]
I believe I've found the problem in my code. The table that it's failing on is a table of numeric key codes to strings names. Because I pass this table on to an untrusted sandbox, I attempted to make the table read only by doing this:

    local makeTableReadOnly = function(tab)
        return setmetatable(tab, {
                __index = tab,
                __newindex = function(t, k, v) end,
                __metatable = false
            })
    end
    local keyNameTable = makeTableReadOnly(keyNameTable)

BUT, this is incorrect, since the first argument for setmetatable() should have been an empty table {}, not the 'tab' table (http://lua-users.org/wiki/ReadOnlyTables). I wouldn't think that it mattered what the table was, and that it would just be ignored, because __index and __newindex are defined. Upon fixing this, everything works as expected.

Thanks for your help, Paul.
