### ISSUE TITLE
hang on tooltip + keypress

### ISSUE THREAD

**Issue by ildar** [pkulchenko/ZeroBraneStudio#557]
When a tooltip/quicktip appears and a user does keypresses, ZBS just hangs or sometimes crashes.

**Comment by ildar** [comment]
quite mysterious but I cannot reproduce today. Though it behaved as
described yesterday. Closing. Sorry.

**Comment by pkulchenko** [comment]
Just in case, what platform and the version number (or commit# if running from the repo)?

**Comment by ildar** [comment]
Linux x86_64 both 1.20 and git HEAD

**Comment by pkulchenko** [comment]
@ildar, please reopen if you find a way to reproduce the issue. If you still see it happening occasionally, one way to get more information is to compile wxlua with debugging (`(cd build; ./build-linux.sh wxwidgets lua wxlua debug)`) and enable coredumps. Then just keep running it as you'd do normally, as this may provide a stacktrace after the next crash. The only flipside is that it will be using the most recent version of wxwidgets (instead of the one used in the current version), but should sill be useful.

**Comment by ildar** [comment]
Thanks
