### ISSUE TITLE
<projectdir>/.zbstudio is not shown in Project-Tab

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#561]
Related to #555 
> packages from `<projectdir>/.zbstudio/packages/*.lua` will be loaded ¹). 

I cannot see the directory `<projectdir>/.zbstudio` in project tab, "Show Hidden Files" is disabled.
(with current zbs checked out from master)
Because of this it's difficult to edit the project-related packages (I can still open them with File/Open)

**Comment by pkulchenko** [comment]
@jjvbsag, you are probably on Linux and since the filetree doesn't show "hidden" files (those that are marked "hidden" by the OS, not bu the IDE), and "dot" files are hidden in Linux, they are not shown. I can probably add a setting, but am hesitant to do this since you can open that file directly as you said (either with File/Open or with Ctrl-P and the filename).

**Comment by jjvbsag** [comment]
No, *nothing* is hidden by the operating system, this is purely convention by the application programmers. Did the following to create a test sample:
```sh
mkdir example
cd example
echo > normal-file.txt
echo > .hidden-file.txt
mkdir normal-dir
mkdir .hidden-dir
```

the ran the following lua script above example
```lua
require"lfs"
for entry in lfs.dir("example") do
	print(entry)
end
```

result output
```
.
normal-file.txt
normal-dir
..
.hidden-dir
.hidden-file.txt
```

This is (beside the order of the entries returned by lfs.dir() ) *identical* on window and linux. Maybe wx has an option, which entries to return on directory reading and this option has different defaults on windows and linux. But it is surely possible to tell wx to return all entries the same way lfs does.

**Comment by pkulchenko** [comment]
I didn't mean to imply that OS hides something (although I can see why it may be read this way). I only meant to distinguish this logic from what's done by the IDE when you use "hide/unhide" feature in the file tree.

wxwidgets treats hidden files/folders separately from all others and since some apps (like git, svn, and some others) keep their files in hidden directories (on Windows it has "hidden" attribute and on other systems it's just by convention as far as I can tell), I thought it would be proper to keep those hidden in the tree.

Try the following patch:

```diff
diff --git a/src/util.lua b/src/util.lua
index 3bffbfd..baf1716 100644
--- a/src/util.lua
+++ b/src/util.lua
@@ -219,7 +219,7 @@ function FileSysGetRecursive(path, recursive, spec, opts)
     -- recursion is done in all folders if requested,
     -- but only those folders that match the spec are returned
     local _ = wx.wxLogNull() -- disable error reporting; will report as needed
-    local found, file = dir:GetFirst("*", wx.wxDIR_DIRS)
+    local found, file = dir:GetFirst("*", wx.wxDIR_DIRS + wx.wxDIR_HIDDEN)
     while found do
       local fname = wx.wxFileName(path, file):GetFullPath()
       if optfolder and ismatch(fname..sep, inmasks, exmasks) then
@@ -236,7 +236,7 @@ function FileSysGetRecursive(path, recursive, spec, opts)
       end
       found, file = dir:GetNext()
     end
-    found, file = dir:GetFirst(spec or "*", wx.wxDIR_FILES)
+    found, file = dir:GetFirst(spec or "*", wx.wxDIR_FILES + wx.wxDIR_HIDDEN)
     while found do
       local fname = wx.wxFileName(path, file):GetFullPath()
       if ismatch(fname, inmasks, exmasks) then
```

**Comment by jjvbsag** [comment]
I will check on monday (I'm home now). I only wonder, why there is `Show '.' files` and `Show hidden files` menu entries in the context menu of the project tree, while they are disabled and non-functional (both on windows and linux). Other Filemanagers and IDE's (e.g. Codelite) have a toggle, whether to show hidden files or not. 

If I'm wrong and this is not not, what `Show hidden files` is indented to do, then I'll like to treat this issue as a feature request to implement a Menu `Show/Hide OS-Hidden files`, which toggles `+ wx.wxDIR_HIDDEN` (and is on Hide by default)

Regards, have a nice weekend

**Comment by pkulchenko** [comment]
@jjvbsag, I've added `showhiddenfiles` option to enable showing hidden files in the project tree.

> I only wonder, why there is `Show '.' files` and `Show hidden files` menu entries in the context menu of the project tree, while they are disabled and non-functional (both on windows and linux).

They are for a different purpose, but I can understand why it may be confusing. It's actually `Hide '.' files` (which means files without extension), but you are probably on a directory and that's why the item is disabled. `Show hidden files` is disabled because you haven't hidden anything yet.

I realize that it may indeed be confused with hidden files in the file system and will see if I can clarify this in the documentation.

**Comment by jjvbsag** [comment]
@pkulchenko  I've added `ide.config.showhiddenfiles=true` to `<projectdir>/.zbstudio/user.lua` and it works as expected. Thanks for the change
Regards Jørgen

**Comment by pkulchenko** [comment]
@jjvbsag, sounds good; you only need to add `showhiddenfiles=true` though as it's mapped to `ide.config` already.

**Comment by jjvbsag** [comment]
> you only need to add `showhiddenfiles=true` though as it's mapped to `ide.config` already.

:question: I find this very confusing. Is there *any* documentation, 
* what variables ¹) are mapped to `...`, `G`, `_G`, `editor` and function environment (`getfenv()`) ? 
* In case of `user.lua`, which variables ¹) are mapped ?
* In case of `package/*.lua` , which variables ¹) are mapped ?

:question:  clueless :question: 

¹) I speak of variables as lua term, which can be any data type including functions

**Comment by pkulchenko** [comment]
> I find this very confusing. Is there any documentation,
>    - what variables ¹) are mapped to ..., G, _G, editor and function environment (getfenv()) ?
>    - In case of user.lua, which variables ¹) are mapped ?
>    - In case of package/*.lua , which variables ¹) are mapped ?

It's actually quite straightforward ;): you only need to reference variables as documented in the [preferences section](https://studio.zerobrane.com/doc-general-preferences).

There are some rare cases, where you *may* need access the spec configuration (`ide.specs.lua`) or call lua functions from an inline package (`package { onRegister = function() table.insert(something, 'else') end }`), in which case `local G = ...` was used to provide access to the global environment from the config file. Starting from v1.21+, this is no longer needed, as the global environment is already available, so those methods can be used directly (I already updated `cfg/user-sample.lua` to reflect that). The processing is exactly the same for all config files.
