### ISSUE TITLE
content shows incorrectly when debug with weak table

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#563]
a = {"A"}
	b = {nil, a}
	rawset(b, 1, b[2])
	assert(b[2] == a and b[1] == a)  --success, b[2] is actually a

After `rawset(b, 1, b[2])`, the watch window or  hover tip shows `{{"A"}, nil}` on `b`, which should be `{{"A"}, {"A"}}` I think. And if `a` is not a table, the showed is correct.

**Comment by pkulchenko** [comment]
That's a "feature" of the pretty-printer: since it's not possible to show self- and cross-references correctly with a literal table, the values are pretty-printed with `nil` values; there is also a comment added if you look at the values in the Console: `{{"A"}, nil} --[[table: 0x03f80938]] --[[incomplete output with shared/self-references skipped]]`.

It's not something specific to weak tables as it's shown this way for all tables. It's possible to change the serializer to show the values the way you want it; let me know if you are interested in the details.
