### ISSUE TITLE
Suggestion: Auto expand the folded/collapsed line after marker navigation

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#595]
1. **Auto expand** the folded/collapsed line of marker.
2. Use **one item** for both bookmark and breakpoint when they are at the same position / line, like editor's margin do.

**Comment by pkulchenko** [comment]
> Auto expand the folded/collapsed line of marker.

@robertlzj, you mean do this when the marker is jumped to and it being hidden because of folded fragment? yes, it may be a good idea.

> Use one item for both bookmark and breakpoint when they are at the same position / line, like editor's margin do.

This is unlikely. The editor component handles it in the editor, but in the markers panel I'd need to create combined icons (for all the combinations, possibly with new markers), which would complicate matters. Also, clicking on the icon in the markers window toggles the marker, which I'd like to keep (and it will be problematic for combined icons).

**Comment by robertlzj** [comment]
> clicking on the icon in the markers window toggles the marker  

I see, it will toggle to **clear** the marker. Which would be operated by mistake click I think.

> combined icons (for all the combinations, possibly with new markers)  

Yes, it's a complicate problem.
There always various point of management : 
  **many-for-one**: marker1 - line0, marker2 - line0;
  or, **one-for-many**: line0 - marker1, marker2 .
Current is fine.

**Comment by pkulchenko** [comment]
> I see, it will toggle to clear the marker. Which would be operated by mistake click I think.

Yes, but it's no different from the current code line and the toggle in the margin. It's a convenient way to clear after getting used to it ;)

**Comment by pkulchenko** [comment]
Should be fixed now; give it a try.
