### ISSUE TITLE
Raspberry Pi 2 with OpenGL support

### ISSUE THREAD

**Issue by ThreeMileJump** [pkulchenko/ZeroBraneStudio#599]
There is a new version of Raspbian with accelerated OpenGL in  X. Love2D now installs and works properly directly from the repositories. Probably the other Lua frameworks will follow shortly.

What is involved in getting ZeroBrane installed on a Raspbian system with OpenGL supported?

**Comment by pkulchenko** [comment]
@ThreeMileJump, are you asking how to get ZBS installed on that version R-Pi-2 or how to get opengl support added to ZBS?

**Comment by ThreeMileJump** [comment]
Hi Paul

I was asking how to get ZeroBrane installed on Raspbian. The OpenGL support
may not be any advantage directly to ZeroBrane, but now love2d and others
work properly, the RPi2 is a much more attractive target and ZeroBrane
would be a superb editor for that platform.

So far, I haven't seen an example of ZeroBrane on Raspbian, so I am
wondering if there are any known issues?

ZeroBrane really is a great tool and much appreciated.

**Comment by pkulchenko** [comment]
@ThreeMileJump, I think the main issue is going to be in building wxwidgets/wxlua that ZBS depends on. I have linux build scripts in the `build/` folder, so you may try running `(cd build/; bash build-linux.sh lua wxwidgets wxlua)` and see if there are any issues. There are several dependencies needed, which you'll find in `build-linux-prep-deb.sh`.

Even if directly building on RPi2 fails, you can still debug scripts/apps running on RPi2 from ZBS running somewhere else, as ZBS supports [remote debugging](https://studio.zerobrane.com/doc-remote-debugging). It's not as convenient as running on the same machine, but still supports exactly the same functionality.

**Comment by pkulchenko** [comment]
I see several people reported [success compiling wxwidgets on RPi](https://www.raspberrypi.org/forums/viewtopic.php?t=8935&p=292883), so it should be possible on RPi2 as well. I just note that you need to install dependencies (like the mentioned `libwxgtk2.8-dev`), but you don't need to build wxwidgets directly as the build script that comes with the IDE will configure and build wxwidges as needed (it will be installed relative to the IDE structure, so it will not pollute your system directories).

**Comment by ardje** [comment]
Hi,

ThreeMileJump schreef op 2016-02-14 03:07:
> I was asking how to get ZeroBrane installed on Raspbian. The OpenGL
> support
> may not be any advantage directly to ZeroBrane, but now love2d and
> others
> work properly, the RPi2 is a much more attractive target and ZeroBrane
> would be a superb editor for that platform.

I've been using ZeroBrane git for a long time on all my exynos 
platforms:
chromebook, xu3, xu4.
Paul already has incorporated the needed patches. So it is a no-brainer 
to compile zerobrane on armhf.

> So far, I haven't seen an example of ZeroBrane on Raspbian, so I am
> wondering if there are any known issues?

You should be looking at armhf in the zerobrane tree, not at raspbian.

> ZeroBrane really is a great tool and much appreciated.

ZeroBrane actually has solved a lot of time for me.
I even have the right "incantations" to start my software with the zb 
debug module included (overriding the #!) using my platform lua, so I 
can snoop into my mistakes:
----
#!/bin/sh
ZB=/home/ard/ZeroBraneStudio
export LUA_INIT="
package.cpath=package.cpath..';$ZB/bin/linux/armhf/clibs53/?.so'
package.path=package.path..';$ZB/lualibs/?.lua;$ZB/lualibs/?/init.lua'
mobdebug=require'mobdebug/mobdebug' mobdebug.coro() mobdebug.start()
"
"$@"
----
Remember that zb debugging is working client server, and the client 
(program-to-be-debugged) connects to the debugserver (zerobrane), and 
the debug server tells the client what to do. You need to wrap posix 
fork and alike with mobdebug.stop() and .start().
So if your love2d has gles support, you can debug it like ^^.
Anyway:
armhf is supported, you can build wxwidgets and all. I use it on 
debian/jessie and ubuntu/trusty.
I haven't seen the intel version in 3 years or so, and I haven't been 
working on intel-as-a-desktop since 2 years.

**Comment by pkulchenko** [comment]
@ardje, that's an interesting idea and a clever use of `LUA_INIT`!

@ThreeMileJump, I've seen [reports of successful compilation of the IDE on RPi](https://love2d.org/forums/viewtopic.php?f=4&t=81925&p=196213&hilit=zerobrane#p196213), so I'm closing this one. I haven't tried it myself, but will have a chance when I get my RPi3.

If you manage to compile it yourself (or run into issues), please update the ticket as it may be useful to others. Thanks.

**Comment by ThreeMileJump** [comment]
@pkulchenko  I have been playing around with the new RPi 3 and just got
back to this.  The scripts as noted above proceed for about 30 mins or so
and give the RPi quite a workout.
Regardless of whether the OpenGL driver is enabled, the build script
declares that it finds no OpenGL drivers.

At the end after building the wxLua, the error message is

makefile:137: recipe for target 'all' failed

The RPi 3 has only been out for 2 weeks and it looks like the experimental
Anholt OpenGL driver is a little unstable with the RPi3. With the RPi 2 I
had a love2d program running for several weeks.
The RPi 3 with OpenGL enabled seems to affect the window management and
some low level chip operation, as it hangs when resizing windows.
Normal Raspbian is stable, but requires OGLES SDL2 library to use love2d.
Unfortunately, swapping between GL and GLES in SLD2  is not convenient.

Overall the anholt driver looks like it will be great, and hopefully any
stability issues with RPi 3 will get ironed out over the coming weeks.

**Comment by ardje** [comment]
Hi, I just found this bugreport, and wanted to add that I've talked to paul since compilation on my XU4 didn't work anymore. The culprit was the support for gl, I have to look into it further why it didn't pickup gles. It actually compiles for me and then complains about a lack of glut ;-).
Paul told me to remove the ';gl;' compile directives for wxlua and wxwidgets after which it seems to work.
I have to look closely to make gles work, but gles was none of my business for now ;-).
