### ISSUE TITLE
how to edit lua script of openresty

### ISSUE THREAD

**Issue by liqile** [pkulchenko/ZeroBraneStudio#600]
I want to edit lua files for an openresty project, but i don't know how to make zerobrane studio auto-complete something like "ngx.say()" or others
thanks

**Comment by pkulchenko** [comment]
@liqile, there is currently no support for Openresty auto-complete, but it shouldn't stop you from adding your own by following the documentation here: https://studio.zerobrane.com/doc-plugin#registering-an-api.

It's better to use [other channels](https://studio.zerobrane.com/community) to ask a question instead of a github ticket.
