### ISSUE TITLE
Replace with regular expression doesn't replace when `highlightselected` package present

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#618]
Example:
Replace in regular, from `{a,b,c,d}` with pattern `(\w)` replace to `[\1] = true`.
Expect result is `{[a] = true, ..}`.
Actual result, just work like search, will select each matched char and next, but won't replace any.

**Comment by pkulchenko** [comment]
@robertlzj, I can't reproduce this; the search happens when you click Enter with the `Find` box being active, but if you click Enter when the `Replace` box is active, then it will do the replacement. Also, if you click on `Replace All` button on the toolbar or use `Alt-Enter` while in the Replace box, then all instances will be replaced.

Reopen if this still doesn't work for you.

**Comment by robertlzj** [comment]
Problem still.
When focus in replace box. Click 'Replace next instance' toolbar button or press enter wont work, just select but not replace. Click 'Replace all' or alt+enter will replace all.
I don't know how can I test more for help..

**Comment by robertlzj** [comment]
Reproduce:
New empty document. past only `a, b`, then search `(\w)`, replace `\1 = true`.
If, only `a`, then the _second_ time replace will take effect.
If, more than one char, like `ab`, will take effect one char per replace.

**Comment by pkulchenko** [comment]
@robertlzj, I think I got what you were saying. So, when the cursor is somewhere before `a`, then the first click on Replace or first Enter in the `replace` field will not replace and will only "find" the occurrence and this is by design to give you a chance to see where the replacement is going to happen. if you already successfully searched before and the selection matches what you are trying to replace, then the replacement will happen on the first click. This is a safety mechanism to allow you to see what you are trying to replace (unless you do `Replace all`).

**Comment by robertlzj** [comment]
No. I know first time to search and select, then replace.
But in the case above, it will never replace. Even click 'replace' continuely, it will select next one, then next next one.. till the last one.

**Comment by robertlzj** [comment]
Reproduce:
If select the whole content `{a,b,c,d}`, then replace will work.
But if select the single char `a`, then replace will jump to next one.
Maybe only happened when the target is single char.

**Comment by pkulchenko** [comment]
Hm, now I'm back to "can't reproduce". Here are my steps.

1. Type `{a, b}`; the cursor is at the end of the line
2. `Ctrl-R` to open find/replace panel
3. Type `(\w)` into the find field
4. `Tab` and type `\1 = true` into the replace field
5. Click `Enter`; now `a` is selected.
6. Click `Enter`; now `a` is replaced with `a = true` and `b` is selected.

Everything is as expected; even when I use `{a}`, I still get `a` replaced after it's selected (so on the second `Enter`). How do your steps differ from mine?

**Comment by robertlzj** [comment]
Exactly the same.
I found the key - 'highlightselected.lua'.
I used this package. It will cause this problem.

**Comment by pkulchenko** [comment]
Confirm the conflict with `highlightselected` plugin; will have a fix shortly.
