### ISSUE TITLE
Pre-configure UI (Hide project window and output window by default)

### ISSUE THREAD

**Issue by qubodup** [pkulchenko/ZeroBraneStudio#644]
For a portable zbstudio package, is it possible to disable the project and/or output windows by default using `cfg/user.lua`?

Or in general: is it possible to configure the enabled UI elements using `cfg/user.lua`?

From looking at `~/.ZeroBraneStudio` I'm guessing it's not possible unless I learn how the wxwidgets source code of zbstudio works and edit files in `src/` directly.

**Comment by pkulchenko** [comment]
It's possible to hide the panels "by default", but the problem is: how do you know that it's no longer a default state and the panels should not be hidden? What if you show them and close the application; how the IDE should know the next time you start it that the panels should not be hidden?

There is a way to check if a panel is present in the layout configuration (which may allow to check if the panel is shown or not), but it uses internal descriptions and is not wrapped into any API, so I'm not very comfortable exposing it (as it's likely to change).

What's your use case for this functionality? I may be able to add `onAppDefault` event to fire on the first (default) run, which will allow you to add whatever logic you want to it; this may also be useful in other cases.

**Comment by qubodup** [comment]
> How do you know that it's no longer a default state and the panels should not be hidden?

I wouldn't mind them being hidden always when zbstudio starts but for the more likely case which you describe, I would assume that `~/.ZeroBraneStudio` keeps track of the latest state.

>There is a way to check if a panel is present in the layout configuration (which may allow to check if the panel is shown or not), but it uses internal descriptions and is not wrapped into any API, so I'm not very comfortable exposing it (as it's likely to change).

That's completely understandable of course.

>What's your use case for this functionality?

The use case is using zbstudio in beginner (game) programming workshops for writing your first game using love2d. These workshops come with a software package that includes love, all what's needed to create an Android .apk, and a text editor (basically a future version of [LoveToAndroid](https://love2d.org/forums/viewtopic.php?t=80513)).

_Please do not hesitate to treat my tickets in whatever is best for your workflow, especially since they are more QA than reports/requests._

**Comment by qubodup** [comment]
By modifying the source of zbstudio 1.3, rather than adding configuration options, I was able to achieve the desired result.

In `src/editor/gui.lua`, l549 I added:

```
  mgr:GetPane("projpanel"):Show(false)
  mgr:GetPane("bottomnotebook"):Show(false)
```

This didn't work for the toolbar (new decision) unfortunately, so I commented out lines 532-535.

I doubt there are many cases where users need zbstudio to look minimal on first run but wanted to share and document just in case.
