### ISSUE TITLE
Stack window displays wrong function name

### ISSUE THREAD

**Issue by georgerbr** [pkulchenko/ZeroBraneStudio#649]
This is on ZeroBrane Studio 1.30 running on Windows 8.1 Pro x64, stock install.

In the minimal working example, I toggle a breakpoint in line 9, start debugging, then step into `f(x)`, which in turn calls `g(t)`; the current line marker in the editor correctly shows the program is in `g(t)`, but the stack window says the program is in `f(x)` – see screenshot.

```
function f(x)
    return g(x)
end

function g(t)
    return t
end

print(f(42))
```

![zb130-stack-step-into](https://cloud.githubusercontent.com/assets/4930759/15554144/fe84e166-2298-11e6-8d98-3460fd7dc936.png)

**Comment by pkulchenko** [comment]
@georgerbr, this is because of the tail call handling in Lua (and LuaJIT); the current stack has been replaced, but LuaJIT may still report this as being the `f` frame (as it can only "guess" as to what the actual function name is). If you want to see the "real" stack, you can disable tail call by changing `g(x)` to `g(x)+0`.

There is not much the IDE or its debugger can do as it only shows what's being reported by the Lua engine that executes the code.

**Comment by georgerbr** [comment]
Ok, thanks!
