### ISSUE TITLE
breakpoints from require('') file are being ignored

### ISSUE THREAD

**Issue by YitzhakSp** [pkulchenko/ZeroBraneStudio#654]
Hello. In my main.lua I **require('')** the file 
<pre><code>
media/sf_Dima/useful_functions/16_20/Lua/misc1.lua
</code></pre>
in the following way:
<pre><code>
require('mobdebug').start()
package.path=package.path .. ';/media/sf_Dima/?.lua'
require ('/useful_functions/16_20/Lua/misc1')
</code></pre>
 
When I set a breakpoint in the main file it works well. However any breakpoints in the required('') file are being ignored. The require() itself works well (I was able to run the program).  Where is the problem?

**Comment by pkulchenko** [comment]
I think the reason for that is that it generates `/media/sf_Dima//useful_functions/16_20/Lua/misc1.lua` path (note the double slash), which is different from `/media/sf_Dima/useful_functions/16_20/Lua/misc1.lua` path that the debugger is checking for (the normalization is only done when there is updir (`..`) reference.

The fix is easy: you shouldn't be using the string you are using in `require`. Try with `require ('useful_functions/16_20/Lua/misc1')` or `require ('useful_functions.16_20.Lua.misc1')`.
