### ISSUE TITLE
console output from Windows whose language is set to chinese, korean or japanese, etc

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#710]
Running `require("ffi").load("advapi")` should error with `cannot load module 'advapi': The specified module could not be found` when Windows language is set to English but if it's set to a non latin (I think?) the output looks like unicode garbage. 

example from Japanese windows: ![](https://i.imgur.com/5JbCVqb.png)

**Comment by pkulchenko** [comment]
@CapsAdmin, I'm not sure there is a proper way to resolve this as it looks like an encoding conflict between the host system and what the console expects as UTF-8 encoding. Since there is no way to know what the host encoding is, unless it happened to be UTF-8, the output will be displayed as shown in the screenshot.

When I print some UTF-8 encoded strings, they are displayed correctly in the output window. I remember seeing a similar report specifically about the encoding for the error messages, but can't find it at the moment.

**Comment by pkulchenko** [comment]
@CapsAdmin, can you include the actual message that *should* be shown (in that non-latin characters)? Also, do you know what encoding is it in? Is it UTF-16?

**Comment by pkulchenko** [comment]
@CapsAdmin, what's the output of `chcp` on that machine? I have posted a potential fix for this in https://github.com/pkulchenko/ZeroBraneStudio/issues/804#issuecomment-331354144 and am curious if it's going to work for you as well...
