### ISSUE TITLE
Installing Braneplug and LuaGUI

### ISSUE THREAD

**Issue by Crasling** [pkulchenko/ZeroBraneStudio#719]
Hey, I am totally new to this and getting trouble instantly. I have tried googling and forums but i cant figure it out.
 Im running the installscripts ZBplugin.lua for both Braneplug and Luagui but nothing actually happens, I have run them a few times without getting any new folders/files. And I cannot find braneplug option in the Zerobrane "edit" option.

**Comment by pkulchenko** [comment]
I won't be able to help with this issue, but maybe @williamwilling has suggestions?

**Comment by williamwilling** [comment]
To install Lua GUI, copy the file `gui.lua` and the folder `gui` (both in the `src` folder) to the `lualibs` folder of your ZeroBrane installation. In ZeroBrane, make sure your interpreter is set to Lua. The following script should now work.

```lua
require 'gui'
window = gui.create_window()
gui.run()
```

At this point, I don't recommend installing Braneplug, since it isn't used for anything but Lua GUI and the above instructions should be easy enough to follow.

**Comment by pkulchenko** [comment]
Ok, thanks @williamwilling for the details. Closing it.
