### ISSUE TITLE
Go-to-line weird behavior

### ISSUE THREAD

**Issue by madmaxoft** [pkulchenko/ZeroBraneStudio#730]
When using the Go-to-line function (Ctrl+G), it tends to behave unexpectedly:
- It has a colon already filled in it, removing the colon makes it change into Go-to-file
- If pressing Enter right after Ctrl+G (that is, go-to-line ":"), the IDE switches project to the root of the C drive
- After entering the line number to go to, the editor shows the line already, but pressing Esc to close the edit-box moves the editor back to where it was before.

I think this behavior is quite confusing and the unified search-and-go-to searchbox that is used here should be replaced with a dedicated simple line entry editbox.

**Comment by pkulchenko** [comment]
1. that's by design as it's one box used for several purpuses
2. looks like a bug; I'll check
3. you need to use Enter to confirm your choice and Esc to cancel it and return to the previous position. It's consistent across all usages of the command bar

> I think this behavior is quite confusing and the unified search-and-go-to searchbox that is used here should be replaced with a dedicated simple line entry editbox.

I don't think it's likely to happen, as having this in one box has several benefits: (1) you get a preview that you can confirm or cancel (you don't get it with a simple box asking for a line number), (2) you can try several without leaving the box, and (3) you can use `file:line` combination at any point, so you can preview any file in the project this way (this is similar to `file@func` and other usages).

**Comment by madmaxoft** [comment]
The problem with needing Enter is that the search box (Ctrl+F) doesn't need one and in fact jumps to the next found match on enter, which makes it inconsistent - Enter needed for go-to-line, but not for search.

**Comment by pkulchenko** [comment]
I realize that, but it's consistent with other usages of the command bar and allows to return to the current position. The difference with search is that it implements incremental search, which requires `Enter` (or `Shift-Enter` to go back), so it's not available to confirm your search.

**Comment by pkulchenko** [comment]
Mattes, fixed the issue with the empty line number.
