### ISSUE TITLE
Debugger connection closed

### ISSUE THREAD

**Issue by yuanshucong** [pkulchenko/ZeroBraneStudio#731]
debugger can't start.
I added require('mobdebug').start() to  script and click Run(F6)
output:
Program starting as '"/home/lab-yuan.shucong/torch/install/bin/th" "/home/lab-yuan.shucong/mc-cnn/test.lua"
Program 'th' started in '/home/lab-yuan.shucong/mc-cnn' (pid: 38350).
/home/lab-yuan.shucong/torch/install/bin/luajit: /home/lab-yuan.shucong/mc-cnn/test.lua:3: Debugger connection closed
stack traceback:
	[C]: in function 'error'
	...an.shucong/ZeroBraneStudio/lualibs/mobdebug/mobdebug.lua:681: in function <...an.shucong/ZeroBraneStudio/lualibs/mobdebug/mobdebug.lua:523>
	/home/lab-yuan.shucong/mc-cnn/test.lua:3: in main chunk
	[C]: in function 'dofile'
	...cong/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
Program completed in 70.56 seconds (pid: 38350).

By the way ,when i click (Project | start debugger server), is says: Can't start debugger server at gpu-1:8172: address already in use.

**Comment by pkulchenko** [comment]
> By the way ,when i click (Project | start debugger server), is says: Can't start debugger server at gpu-1:8172: address already in use.

This looks like you have some other application using the port 8172 and it prevents the debugger server from starting and that's why the debugging doesn't work. You can check what process is using the port by running `lsof -i tcp:8172` (according to [this answer](http://superuser.com/questions/42843/finding-the-process-that-is-using-a-certain-port-in-linux)). If it's another copy of the IDE running, you can stop it, but if it's some other process, you can re-configure the IDE to use a different port number for debugging by setting `debugger.port=8175` or something similar in the config (and restarting the IDE). You will also need to add the same port number to the `start` call: `require('mobdebug').start(nil, 8175)`.
