### ISSUE TITLE
Outline window doesn't show tables

### ISSUE THREAD

**Issue by AnotherWTF** [pkulchenko/ZeroBraneStudio#737]
Some other IDE's show both functions and tables in the outline window (e.g Eclipse with Lua perspective). This would be helpful particularly with non-local tables.

**Comment by pkulchenko** [comment]
Do you have a screenshot of how it's done in Eclipse?

I think it's going to be problematic for several reasons: there is no specific token in the lexer to refer to (as there is for functions), the table definition doesn't open a new scope, so more parsing is required to find where the table ends, there is going to be a parsing penalty to find these functions for all the users who don't need this, functions look like a natural blocks of code to show in the Outline and tables are not.

I may reconsider these points if someone comes up with the implementation (so that I can look at the results), but it's not something I plan to work on any time soon.

**Comment by AnotherWTF** [comment]
Here is a screenshot from Eclipse. Small icons in the outline indicate type and scope. Local identifiers are red.
![rfxtrx lua - eclipse](https://cloud.githubusercontent.com/assets/25824005/23035072/fbbc4c64-f44b-11e6-96a9-997d4dcaa995.png)

**Comment by pkulchenko** [comment]
Ok; thank you for the screenshot. This probably needs to be done in a similar way for all the variables, not just for tables.
