### ISSUE TITLE
Wrong floating point numbers in watch expressions

### ISSUE THREAD

**Issue by rm-code** [pkulchenko/ZeroBraneStudio#739]
I'm loading these values from tables in another lua file:
```
volume     = 2.3
volume     = 3.1
volume     = 4.3
volume     = 0.5
```
When I watch them in ZeroBrane's debug mode it shows them like this:
![bildschirmfoto 2017-02-19 um 23 08 27](https://cloud.githubusercontent.com/assets/11627131/23107181/d689ee6a-f6f8-11e6-81b8-c282f74ee766.png)

**Comment by pkulchenko** [comment]
This is the side-effect of using `%.17g` in the serializer, which is needed for the correct round-trip of the serialized values. What you see is the closest decimal representation of the stored values for those numbers. If we use `%.16g` format instead of `%.17g` in the serializer, you won't see that issue, but that format is not sufficient for the preserving all the significant bits in double values.

I'll see if I can tweak the formatting to show expected values in the Watch/Stack values; I think I'll still keep the original (`%.17g`) values in the Console.

**Comment by pkulchenko** [comment]
@rm-code, I pushed the fix to https://github.com/pkulchenko/ZeroBraneStudio/tree/stack-watch-expansion, which will be merged to master soon. You may want to check how the changes work for you.

**Comment by pkulchenko** [comment]
@rm-code, these changes have been merged into master; the format can be controlled with `debugger.numformat` option.

**Comment by rm-code** [comment]
@pkulchenko Thank you! I didn't find any time to test them this week so my apologies for not responding earlier.
