### ISSUE TITLE
Breakpoints not triggering for subprocess/child process created by fork

### ISSUE THREAD

**Issue by janardhannarayana** [pkulchenko/ZeroBraneStudio#765]
After creating the child process using posix fork, breakpoints are not triggering inside the child process. 
I have added the  mobdebug.start(),   mobdebug.coro() in the subprocess lua script, but as the already one dbugging server is running it is refused to start new one. Is there any way to debug this?

**Comment by pkulchenko** [comment]
@janardhannarayana, this is by design as the IDE only works with one session at a time, so requests to start a second session are rejected (and the breakpoints and all other features won't work until the session is started).

I have an extension for the IDE that enables debugging support for multi-VM/multi-state configuration; I'll add a page to the documentation to describe that in details, but you can contact me (email in the profile or on the project website) for pricing and licensing information.
