### ISSUE TITLE
Can't set watch for '/home/user/luadev/walker': No space left on device

### ISSUE THREAD

**Issue by cpeosphoros** [pkulchenko/ZeroBraneStudio#778]
> Steps to reproduce the issue as well as the expected result. Screenshots also help.
Freshly installed ZeroBrane.

Just open any lua file. That message will show up in the Output pane, for the **folder** containing the file, not for the file itself.

Of course it doesn't cause any harm at all, but it's quite annoying for large projects.

I'll be glad to provide any more information if needed.

> Your operating system and the IDE version

Linux Mint 18.1
ZeroBrane Studio (1.60; MobDebug 0.648)

> Any relevant configuration from the config file, if you cannot reproduce the issue with an empty config.
> Any relevant plugins, if you cannot reproduce the issue without plugins.

None

**Comment by pkulchenko** [comment]
@cpeosphoros, is there space left on the device? This message should only be shown once per path as it's being added to a black list and should not be reported until the IDE is restarted.

Yes, it's reported for the folder as the watch is set on the folder itself, but it should only be reported on (sub-)folders under the project directory and not outside of it.

You can disable watches by setting `filetree.showchanges = false` in the config (see https://studio.zerobrane.com/doc-general-preferences#projectfiletree), but I'd be interested to explore why exactly this message is thrown.

Does it show it on any folder on that device? Is there anything unusual about that device? Can you try opening files on a different disk to see if the same error is shown?

**Comment by cpeosphoros** [comment]
> This message should only be shown once per path as it's being added to a black list and should not be reported until the IDE is restarted.
> Yes, it's reported for the folder as the watch is set on the folder itself, but it should only be reported on (sub-)folders under the project directory and not outside of it.

>Does it show it on any folder on that device?

That is the exact behavior, now that you mentioned it. Opening any Lua file in subfolders of the current project raises the message. Opening Lua files elsewhere in the same device doesn't.

> Is there space left on the device? Is there anything unusual about that device?

It's a 2 T Samsung regular SATA device,with a healthy SMART report, mounted as `/dev/sda5 / ext4 rw,noatime,nodiratime,errors=remount-ro,data=ordered 0 0`, with about 1.5 T of free space.

```
Can't set watch for '/home/user/luadev': No space left on device
Can't set watch for '/home/user/luadev/walker': No space left on device
```
Those were the messages with the original project.
I closed all the files, closed the IDE, copied the project to a flash drive, than got this:
```
Can't set watch for '/media/user/7A90-A40D/luadev': No space left on device
Can't set watch for '/home/user/7A90-A40D/luadev/walker': No space left on device
```
I noticed that the first message appears right after "Choose project..." closes, without even opening any Lua files.

Same thing with a different project, same thing with empty folders, etc. At all scenarios, opening a file outside the current project doesn't raise the message.

I think it may be something about my machine, not about the devices, actually.

Thank you for the quick answer and also for the workaround. I've just installed ZB and I'm still starting to see what I can configure, which interesting plugins are out there, etc.

Anyways, at first glance, it seems to be a very nice IDE. I look forward to enjoy using it.

**Comment by pkulchenko** [comment]
@cpeosphoros, thank you for the details. Yes, opening files outside of the project tree shouldn't trigger any errors as watches are not added there. Choosing a new project sets at least one watch (for the project tree), so this is why you see the message.

I'm still not sure why you get these errors and the issue seems to be below the Lua level in this case. You can try running this directly in the Local console: `local watcher = wx.wxFileSystemWatcher(); watcher:SetOwner(ide:GetMainFrame()); return watcher:Add(wx.wxFileName.DirName("/home/user/luadev"), wx.wxFSW_EVENT_CREATE + wx.wxFSW_EVENT_DELETE + wx.wxFSW_EVENT_RENAME), wx.wxSysErrorMsg()` to see the result and the error message (which is probably going to be what you already have seen).

> Thank you for the quick answer and also for the workaround. I've just installed ZB and I'm still starting to see what I can configure, which interesting plugins are out there, etc.

You can check the plugin repository (https://github.com/pkulchenko/ZeroBranePackage); some of the popular plugins are [DocumentMap](https://github.com/pkulchenko/ZeroBranePackage/blob/master/documentmap.lua), [UniqueTabName](https://github.com/pkulchenko/ZeroBranePackage/blob/master/uniquetabname.lua), [CloneView](https://github.com/pkulchenko/ZeroBranePackage/blob/master/cloneview.lua), [ProjectSettings](https://github.com/pkulchenko/ZeroBranePackage/blob/master/projectsettings.lua), [SyntaxCheckOnType](https://github.com/pkulchenko/ZeroBranePackage/blob/master/syntaxcheckontype.lua), and [HighlightSelected](https://github.com/pkulchenko/ZeroBranePackage/blob/master/highlightselected.lua).

**Comment by cpeosphoros** [comment]
`false	No space left on device`

**Comment by pkulchenko** [comment]
This is what's returned by wxwidgets methods, so I don't have much control over it (or a way to troubleshoot it).

Maybe there is a shortage of inodes (can be checked by `df -i /`)? There are [plenty of reports on this issue](https://www.google.com/search?q=%22No+space+left+on+device%22+reported+linux+mint&ie=utf-8&oe=utf-8), but other than inodes I don't see what else may be relevant to this case.

**Comment by cpeosphoros** [comment]
```
Filesystem       Inodes   IUsed    IFree IUse% Mounted on
/dev/sda5      61014016 1770600 59243416    3% /
```
Doesn't seems to be the case. Anyways, feel free to close the issue. It's probably something beyoond ZB's scope.

As I said, I can live with it, more so being able to shut up the messages.

Thanks anyways, and congratulations on this very good software.

**Comment by pkulchenko** [comment]
Sounds good. For others who may be checking on this, the workaround is to disable watches by setting `filetree.showchanges = false` in the config (see https://studio.zerobrane.com/doc-general-preferences#projectfiletree). If someone knows what may be causing this, leave a comment in this ticket.
