### ISSUE TITLE
`else` is de-indented on Enter after empty line

### ISSUE THREAD

**Issue by 4aiman** [pkulchenko/ZeroBraneStudio#781]
This happens every time there's an empty line above a line starting with [icode]else[/code] keyword.
I don't know how to properly describe this, so here's a gif for ya:
![gif](https://www.dropbox.com/s/32h4kfb413a72kz/test.gif?dl=1)

**Comment by pkulchenko** [comment]
Yes, it's mostly by design as the indentation logic looks at the previous line and in this case it doesn't have any indent, so `else` is moved to the left. You have three options: (1) make sure that the previous line has proper indentation, (2) move cursor instead of using Enter, or (3) reformat the code (Ctrl-I) after you type the `else` clause.

I looked previously at modifying the logic to handle this case, but it was too complicated and ran into other edge cases that don't exist with the current solution.
