### ISSUE TITLE
Yield out from main chunk to IDE when debug

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#801]
```lua
assert(false==pcall(function()coroutine.yield()end))
	--Error 'attempt to yield across C-call boundary' in running mode
print'Never reach here in debug mode'
```

**Comment by pkulchenko** [comment]
@robertlzj, interesting; can confirm this happening, but not yet sure why... It's the same with all versions of Lua I tested, so doesn't seem to be a fluke...

**Comment by pkulchenko** [comment]
@robertlzj, I figured out what's happening. If you add `require('mobdebug').start()` to the beginning of your script and "Run" it, you get debugging and the behavior will be exactly as you expect.

The situation with F5/Debug is different, because the script is loaded into a coroutine and the execution of it is done in a coroutine, so when  you run `yield()`, it actually doesn't fail with the error, but successfully yields out of that coroutine created by the debugger. This also completes the debugger process (as it never resumes the script), so that's why you see this behavior.

I'm not sure it's a bug, even though the behavior between Run and Debug is slightly different. I've tried to make them both close to each other, but there are some small differences and you ran into one of them.

Here is the patch that will trigger an error, even though it's a different one from what you'd expect:

```lua
diff --git a/lualibs/mobdebug/mobdebug.lua b/lualibs/mobdebug/mobdebug.lua
index 23a4705..8dbca56 100644
--- a/lualibs/mobdebug/mobdebug.lua
+++ b/lualibs/mobdebug/mobdebug.lua
@@ -1157,14 +1157,16 @@ local function controller(controller_host, controller_port, scratchpad)
       coro_debugee = corocreate(debugee)
       debug.sethook(coro_debugee, debug_hook, HOOKMASK)
       local status, err = cororesume(coro_debugee, unpack(arg or {}))
-
       -- was there an error or is the script done?
       -- 'abort' state is allowed here; ignore it
       if abort then
         if tostring(abort) == 'exit' then break end
       else
-        if status then -- normal execution is done
-          break
+        if status then -- no errors
+          if coroutine.status(coro_debugee) == "suspended" then
+            error("attempt to yield into the debugger", 3)
+          end
+          break -- normal execution is done
         elseif err and not string.find(tostring(err), deferror) then
           -- report the error back
           -- err is not necessarily a string, so convert to string to report
```

It's still different from what you'd expect, but at least it doesn't make the script to die silently. If you want to use debugging and get the *same* result as with Running, then add `require('mobdebug').start()` to your script and use Run.

**Comment by robertlzj** [comment]
1. Yes, I see different between Run and Debug from the second return value of  `coroutine.running()`, `true` when Run, `false` when Debug.
Means the main chunk even in Run mode is also a coroutine?
2. Also, why `coroutine.running()` returns a second boolean value even in Lua 5.1?
I see it is added from Lua 5.2 by IDE's tooltip.
3. I use `coroutine.running()` to test if current function environment is a coroutine, but now I need to use `debug` lib?
4. After add `require('mobdebug').start()` then Run, the breakpoint not work as in Debug mode. I get "the same result" true 😄 Need I apply the patch first?

**Comment by pkulchenko** [comment]
>  Yes, I see different between Run and Debug from the second return value of coroutine.running(), true when Run, false when Debug. But this means the main chunk even in Run mode is also a coroutine?

Technically yes, but you can't really yield from it as it is the "main" thread (the second returned value is "true" for it and will be "false" for any other coroutine).

>  Also, why coroutine.running() returns a second boolean value even in Lua 5.1? (if Lua Interpreter \ 'Lua' means 5.1). I see it is added from Lua 5.2 by IDE's tooltip.

It's because the default Lua 5.1 interpeter is actually a LuaJIT interpreter compiled with Lua 5.2 compatibility, so it has some of the behaviors from Lua 5.2 and this is one of them.

You can always configure the IDE to use Lua 5.1 interpreter if you have it installed locally.

> I use coroutine.running() to test whether current function environment is a coroutine, but now I need to use debug lib?

No, just check if it returns `nil` (which is the main thread in Lua 5.1) or if the second return value is `true` (which is the main thread in Lua 5.2+).

> After add require('mobdebug').start() then Run, the breakpoint not work as in Debug mode. I get "the same result" true~ I didn't see any new commit. Need I apply the patch first?

What breakpoint didn't work? I set a breakpoint on the last `print` line and the debugger stops there for me as expected (with the patch). Without the patch the control doesn't get there as the script is aborted on the line with `coroutine.yield`.

**Comment by robertlzj** [comment]
I see ( question 4 ). No more problem. Thank you. 😄
