### ISSUE TITLE
output: additional jumpto patterns as config or ide function

### ISSUE THREAD

**Issue by pixeljetstream** [pkulchenko/ZeroBraneStudio#881]
recently pushed a change to estrela that added a few more filename/line number detection when clicking error messages in output.
Maybe add possibility to define patterns in the user config, or as function that the plugins can call at initialization time (for example glsl/hlsl compilers etc.)?

**Comment by pkulchenko** [comment]
Christoph, what are those additional patterns?

I was thinking about making it more configurable, but wasn't sure if providing a mask is enough, as file/line/position may be in different order, so having a function is probably necessary. Maybe need to add a callback and if it's not handled, then use the default processing?

**Comment by pkulchenko** [comment]
@pixeljetstream, any details on the patterns?

**Comment by pixeljetstream** [comment]
Hi Paul,
maybe allow to register both function and string?
here is the change for the pattern
https://sourceforge.net/p/estrelaeditor/code/ci/eded52d26e33a50ec277d3c825b7ff9f2a1dbaf2/

**Comment by pkulchenko** [comment]
I think I can do that; the string is a bit problematic because of the order, but assuming that it returns `file, line [, pos]`, we can make it work. If the order is different, then the function that returns in that order should work as well.

**Comment by pkulchenko** [comment]
BTW, If you want to continue working on the estrela branch and keep it in sync with ZBS, you may want to push your changes to a branch, which I can then merge and you can pull the changes from the repo. Otherwise the diverging trees will end up in a flurry of merge commits, which will make it look ugly. I'll implement the changes, but you may want to force push them to keep the repos in sync when they are implemented.
