### ISSUE TITLE
ZBS sometimes blocks folders from being deleted

### ISSUE THREAD

**Issue by Kdansky** [pkulchenko/ZeroBraneStudio#914]
When I have a file open in ZBS that is in a folder, but then switch git (gitkraken to be specific, but I doubt it matters) to another branch, where that folder does not exist because all files in it are branch-specific, then ZBS keeps the folder open in the project view, and that also prevents the folder from being deleted on the file system, resulting in an undeletable zombie folder. Windows 10 is very confused about that and asks for admin permissions to delete, but that doesn't work either.

The solution is to close and restart ZBS, which frees the handle to the folder, and allows explorer.exe to clean it up. ZBS 1.70

**Comment by pkulchenko** [comment]
@Kdansky, I suspect it happens because the IDE monitors the folder for changes in it (files added/renamed/deleted), which "locks" the folder from the OS perspective. You can disable the monitoring by setting `filetree.showchanges=false` in the config (see https://studio.zerobrane.com/doc-general-preferences#projectfiletree), which will avoid any locks on the folder. You can still refresh the files when something changes by using right click in the file tree and selecting "Refresh" from the menu.

Let me know if this doesn't resolve the issue.

**Comment by pkulchenko** [comment]
Another option is to switch the project before deleting/moving the project folder.
