### ISSUE TITLE
Suggestion. Change variable context in debug when select special stack

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#924]
Currently, seems could only access variable value from stack window tree if it's not at top stack level. In other words, editor area could only show-tip and evaluate of variable at top stack level.

I think, if select any stack, then could access variable value from editor area, it's more visual.

**Comment by pkulchenko** [comment]
It's an interesting idea, but it's problematic, because users may unwittingly select a frame in the stack window and then be surprised by the results that are showing variables from a different frame.

The stack frame is also redrawn after each step or stop on a breakpoint, so if the second frame is selected, should the second still be selected if it's a different method? Or should it always be the first one after each step until it's manually set by the user?

There is (an undocumented) way to do this from the remote console: using `a --{stack=2}` instead of `a`, will show the value of `a` variable at the second frame in the stack (and so on).

I'll close it for now, but will think if there is a way to add this to the UI cleanly. If you have other suggestions, don't hesitate to update the ticket.

**Comment by robertlzj** [comment]
I think if the lower stack frame is read only, then any operations like run / step should update and activate the top one.
Meanwhile, add support that user could watch variable in specify frame from watch window (also could do this from remote console), without consider about activated stuff.
Means:
- Binding watch variable to specify frame or top frame.
e.g. Add watch from frame window, or from editor area.
- Change variable context to active frame.
It's not necessary but some convenience to get value tip and add to watch variable with active frame friendly.

**Comment by pkulchenko** [comment]
> I think if the lower stack frame is read only, then any operations like run / step should update and activate the top one.

It's not read-only. You can modify the values in other frames using the same syntax: `a[2] = 'new value' --{stack=2}` will modify the value of `a` table in the second frame.

> Meanwhile, add support that user could watch variable in specify frame from watch window (also could do this from remote console), without consider about activated stuff.

I understand that, but what would be the use case if the same values are accessible from the stack window?

**Comment by robertlzj** [comment]
OK, even it's editable. I think it could be the first one after each step.
I didn't find a reason to fix variable context to the selected stack frame, if I could fix to watch the variable on that frame.
Unless user want to fallback to lower frame, that would be another branch manager system.

> what would be the use case if the same values are accessible from the stack window?

A little convenience, like what shortcut / favorite do - organize needed variables in watch window instead of from a long variable list on a long stack frame tree.
And watch window works only on top frame, is a little localization I think.
