### ISSUE TITLE
wxLua modules

### ISSUE THREAD

**Issue by freeroamrp** [pkulchenko/ZeroBraneStudio#945]
Why are some modules from the following list not available?
`wxadv, wxaui, wxbase, wxcore, wxgl, wxhtml, wxmedia, wxnet, wxstc, wxxml, wxxrc`

For example, very useful `wxxml` module is not available:
![wxxml is nil](https://user-images.githubusercontent.com/43248984/46622893-a7dfcc80-cb34-11e8-8f3e-1f73c4ba2e59.png)

Why i must add dependencies to the package if such functionality is available in wxLua?

**Comment by pkulchenko** [comment]
Actually, most of these modules are included in the wx library shipped with the ide; here is the full list: `stc;gl;html;aui;adv;core;net;base`. Of those you listed only wxmedia, wxxml and wxxrc are not included, because they are not used in the IDE itself. You can definitely compile your version of wxlua that includes those modules either using the build scripts that comes with the IDE (`build/build-*.sh`) or using the make file that comes with wxlua.

If you need details on what to modify in the build script to enable those modules, let me know.
