### ISSUE TITLE
error loading module 'socket.core' from core.dll on 32-bit application

### ISSUE THREAD

**Issue by Xottab-DUTY** [pkulchenko/ZeroBraneStudio#980]
I digged through the issues and found that this may happen because my LuaJIT is 64 bit...

But my [latest LuaJIT 2.1](https://github.com/LuaJIT/LuaJIT/tree/v2.1) that I'm using is 32-bit. What can I do to fix the issue? I can provide more info that you may need.

By the way, where I can get luasocket x64? The [link ](https://download.zerobrane.com/luasocket-win64.zip)is broken.

And why ZBS can't just have 64-bit libraries in its distribution, huh?

**Comment by pkulchenko** [comment]
Any 32bit application should only be loading 32bit libraries/binaries and the same for 64bit. THe only exception is on macOS where it's possible to load universal binaries.

I'm not sure what exactly the issue is in your case, but you can use [Dependency walker](http://www.dependencywalker.com/) to trace the chain of dynamic libraries being loaded and any issues during the load that are being reported.

The updated 64bit libraries are here (also includes luasec): https://download.zerobrane.com/misc/luasec-0.6-openssl-1.0.2o-luasocket-3.0-win64.zip
