### ISSUE TITLE
mixed stdout / stderr does not come in correct order

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#983]
Because I had issues, I wrote this small test script.

```lua
local sprintf=string.format
local function iprintf(...)
	io.write(sprintf(...))
end
local function eprintf(...)
	io.stderr:write(sprintf(...))
end

for i=1,20 do
	iprintf("stdout %d\n",i);
	eprintf("stderr %d\n",i);
	if i==10 then
		io.stdout:setvbuf 'no'
		io.stderr:setvbuf 'no'
	end
end
```
Expected result is to have 1..10 in unspecified order, 11..20 clean interleaved stdout and stderr.

Output on command line is
```text
stdout 1
stderr 1
stdout 2
stderr 2
stdout 3
stderr 3
stdout 4
stderr 4
stdout 5
stderr 5
stdout 6
stderr 6
stdout 7
stderr 7
stdout 8
stderr 8
stdout 9
stderr 9
stdout 10
stderr 10
stdout 11
stderr 11
stdout 12
stderr 12
stdout 13
stderr 13
stdout 14
stderr 14
stdout 15
stderr 15
stdout 16
stderr 16
stdout 17
stderr 17
stdout 18
stderr 18
stdout 19
stderr 19
stdout 20
stderr 20
```
which is better than expected.
Output, when executed from within Scite is

```text
stderr 1
stderr 2
stderr 3
stderr 4
stderr 5
stderr 6
stderr 7
stderr 8
stderr 9
stderr 10
stdout 1
stdout 2
stdout 3
stdout 4
stdout 5
stdout 6
stdout 7
stdout 8
stdout 9
stdout 10
stdout 11
stderr 11
stdout 12
stderr 12
stdout 13
stderr 13
stdout 14
stderr 14
stdout 15
stderr 15
stdout 16
stderr 16
stdout 17
stderr 17
stdout 18
stderr 18
stdout 19
stderr 19
stdout 20
stderr 20
```
which is pretty perfect the expected behaviour.

But from ZBS I get
```text
stdout 1
stdout 2
stdout 3
stdout 4
stdout 5
stdout 6
stdout 7
stdout 8
stdout 9
stdout 10
stdout 11
stdout 12
stdout 13
stdout 14
stdout 15
stdout 16
stdout 17
stdout 18
stdout 19
stdout 20
stderr 1
stderr 2
stderr 3
stderr 4
stderr 5
stderr 6
stderr 7
stderr 8
stderr 9
stderr 10
stderr 11
stderr 12
stderr 13
stderr 14
stderr 15
stderr 16
stderr 17
stderr 18
stderr 19
stderr 20
```
which is unexpected and does not give the expected serialization of outputs.

(This is all with ZBS 1.80 on xubuntu 16.04)

**Comment by pkulchenko** [comment]
@jjvbsag, that's a good point, but the reason for this order is ZBS is simple: the streams are processed in stdout/stderr order, so while stdout is being processed, more content is received for it, which is being shown, before stderr is processed. Since none of the content has timestamps to re-order it, they are displayed in the order in which they are processed.

It *may* be possible to change this, but it would require more frequent checks for any new content in the streams and more frequent switches between the two, which is likely to consume more CPU. I don't see any reason for changing the way it's implemented. Do you have a specific use case that requires the strict ordering?

The logic is in `ProcessStreams()` method (`src/editor/output.lua`), so you can play with it to see if you can make it return better results.

**Comment by jjvbsag** [comment]
> Do you have a specific use case that requires the strict ordering?

Yes. Long testing scripts, which do some output (the function name differ, but I translate to the ones used in above example).

```lua
iprintf("do test 1\n") test1()
iprintf("do test 2\n") test2()
iprintf("do test 3\n") test3()
iprintf("do test 4\n") test4()
iprintf("do test 5\n") test5()
```
and 
```lua
function test3()
    local fd=io.open("bla")
   if not fd then eprintf("open bla failed\n") end
   :::
end
```
Normally I'd get
```text
do test 1
do test 2
do test 3
open bla failed
do test 4
do test 5
```
but in ZBS I'll get
```text
do test 1
do test 2
do test 3
do test 4
do test 5
open bla failed
```
which caused trouble to identify the failed test case.

(In reality I use a test framework, this is only to illustrate the problem)

**Comment by pkulchenko** [comment]
You can add `debug.getinfo(1, "n").name` to your error message to show the name of the function or send the output to the same stream, in which case the consistency will be maintained.

I'll take a look at re-organizing the stream processing for getting more consistent results, but it's likely to have some negative consequences.

**Comment by pkulchenko** [comment]
I checked, but since the streams are checked from the IDLE event, but the time the first event is handled, the entire output content is already available from your script (all 211 bytes), so it's not possible to read it in the same order as the stdout and stderr generate. I don't think wxwidgets provides any other way to detangle them.

**Comment by jjvbsag** [comment]
@pkulchenko Please don't put too much work into this. I just wanted to report it, and if there had been a simple fix, it would have been nice. But its no blocker and I can live with it.

**Comment by pkulchenko** [comment]
@jjvbsag, closing this, as I don't see any way to improve what's already available. Not ideal, so if you find a way to deal with it, please update or re-open the ticket.
